app/private/__init__.py
#!/usr/bin/python
from flask import Blueprint

private_bp = Blueprint("private", __name__, template_folder = "templates/private", static_folder = "static/private")

from . import routes

app/private/routes.py
#!/usr/bin/python
from flask import render_template, redirect, url_for
from flask_login import logout_user, login_required

from . import private_bp
from app import login_manager
from app.common.models import User

@private_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("public.index"))

@private_bp.route("/usuario")
@login_required
def logueado():
    return render_template("students.html")

@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(int(user_id))

app/private/templates/private/base/user.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Links -->
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/base.css')}}">
    <link rel="icon" href="{{url_for('static', filename = 'media/logo.png')}}" type="image/png">
    <link rel="stylesheet" href="{{url_for('private.static', filename = 'css/user.css')}}">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">

    <title>Usuario</title>
  </head>
  <body>
    <header style="position: fixed; width: 100%;">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand" href="#">{{current_user.perfil}}</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link valor" href="#art1">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Academico
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item valor" href="#art2">Notas</a>
                	<a class="dropdown-item valor" href="#art3">Materias</a>
              </div>
            </li>
          </ul>
          <li class="nav-item dropdown" style="list-style: none">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{current_user.name}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	              <a class="dropdown-item valor" href="#art4">Perfil</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('private.logout')}}">Cerrar Sesion</a>
            </div>
          </li>
        </div>
      </nav>
    </header>
    <div style="padding: 5% 0">
      {% block content %}
      {% endblock %}
    </div>
    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Scripts -->
    <script type="text/javascript" src="{{url_for('static', filename = 'js/base.js')}}"></script>
    <script type="text/javascript" src="{{url_for('private.static', filename = 'js/user.js')}}"></script>
  </body>
</html>

app/private/templates/private/students.html
{% extends "base/user.html" %}
{% block content %}
<div class="all">
<div class="dates">
    <div class="foto">
        <div style="width: 100px; height: 100px; background-color: white"></div>
    </div>
    <p><spam style="font-weight:bold">Codigo: </spam>{{current_user.id}}</p>
    <p><spam style="font-weight:bold">Nombre Completo: </spam>{{current_user.name}}</p>
    <p><spam style="font-weight:bold">Institución Educativa: </spam>{{current_user.ie}}</p>
    <p><spam style="font-weight:bold">Correo Electronico: </spam>{{current_user.email}}</p>
</div>
<div class="documents">
    <article id="art1">
        <h1>Bienvenido <span style="font-style:italic">{{current_user.name}}</span></h1>
        <h3>Tus Materias</h3>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Codigo</th>
              <th scope="col">Profesor</th>
              <th scope="col">Materia</th>
            </tr>
          </thead>
        </table>
    </article>
    <article id="art2">
        <h1>Notas</h1>
        <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Materia</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 1</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 2</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 3</th>
              <th scope="col">Promedio</th>
              <th scope="col">Accion</th>
            </tr>
          </thead>
        </table>
    </article>
    <article id="art3">
        <h1>Materias</h1>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Profesor</th>
              <th scope="col">Materia</th>
              <th scope="col">Accion</th>
            </tr>
          </thead>
        </table>
    </article>
</div>
</div>
<script>
</script>
{% endblock %}

app/private/templates/private/teachers.html
{% extends "user.html" %}
{% block content %}
<div class="all">
<div class="dates">
    <div class="foto">
        <div style="width: 100px; height: 100px; background-color: white"></div>
    </div>
    <p><spam style="font-weight:bold">Codigo: </spam>{{user[0]}}</p>
    <p><spam style="font-weight:bold">Nombre Completo: </spam>{{user[1]}}</p>
    <p><spam style="font-weight:bold">Institución Educativa: </spam>{{user[2]}}</p>
    <p><spam style="font-weight:bold">Correo Electronico: </spam>{{user[3]}}</p>
    <p style="font-weight: bold">{{fecha}}</p>
    <p style="font-weight: bold">{{hora}}</p>
</div>
<div class="documents">
    <article id="art1">
        <h1>Bienvenido <span style="font-style:italic">{{user[1]}}</span></h1>
        {% if tams > 0 %}
        {% for i in range(tams) %}
        {% if tam[i] > 0 %}
          <h3>Tus Estudiantes de {{materia[i][2]}} son:</h3>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Estudiante</th>
            </tr>
          </thead>
          <tbody>
            {% for j in range(tam[i]) %}
              <tr>
                <th scope="row">{{estudiantes[i][j][0]}}</th>
                <th scope="row">{{estudiantes[i][j][1]}}</th>
              </tr>
            {% endfor %}
            {% else %}
            <h3>No tienes Estudiantes de {{materia[i][2]}}</h3>
            {% endif %}
          </tbody>
        </table>
        {% endfor %}
        {% else %}
        <h3>No dictas ninguna materia</h3>
        {% endif %}
    </article>
    <article id="art2">
        <h1>Notas</h1>
        {% if tams > 0 %}
        {% for i in range(tams) %}
        {% if tam[i] > 0 %}
        <h3>{{materia[i][2]}}</h3>
        <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
            	<th scope="col">Codigo</th>
              <th scope="col">Estudiante</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 1</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 2</th>
              <th scope="col">Porcentaje</th>
              <th scope="col">Nota 3</th>
              <th scope="col">Promedio</th>
              <th scope="col">Accion</th>
            </tr>
          </thead>
          <tbody>
            {% for j in range(tam[i]) %}
            {% if promedio[i] < 30 %}
              <tr class="table-danger">
            {% elif promedio[i] >= 30 and promedio[i] < 35 %}
              <tr class="table-warning">
            {% else %}
              <tr class="table-success">
            {% endif %}
                <th scope="row">{{estudiantes[i][j][0]}}</th>
                <th scope="row">{{estudiantes[i][j][1]}}</th>
                <td>{{notas[i][0]}}%</td>
                <td>{{notas[i][1]}}</td>
                <td>{{notas[i][2]}}%</td>
                <td>{{notas[i][3]}}</td>
                <td>{{notas[i][4]}}%</td>
                <td>{{notas[i][5]}}</td>
                <td>{{promedio[i]}}</td>
                <td>
                  <button type="button" class="btn btn-warning" role="link" onclick="window.location='/addedit/2/'">Modificar</button>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h3>No tienes Estudiantes de {{materia[i][2]}}</h3>
        {% endif %}
        {% endfor %}
        {% else %}
        <h1>No tienes materias registradas<h1>
        {% endif %}
    </article>
    <article id="art3">
        <h1>Materias</h1>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Materia</th>
              <th scope="col">Accion</th>
            </tr>
          </thead>
          {% if materias > 0 %}
          <tbody>
            {% for i in range(materias) %}
                  <tr>
                    <th scope="row">{{materia[i][1]}}</th>
                    <td>{{materia[i][2]}}</td>
                    <td>
                      <button type="button" class="btn btn-warning" role="link" onclick="window.location='/addedit/2/1/{{materia[i][0]}}/{{user[0]}}'">Cambiar</button>
                      <button type="button" class="btn btn-danger" role="link" onclick="window.location='/materias/2/2/{{materia[i][0]}}/{{user[0]}}/a/a'">Cancelar</button>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
                {% endif %}
        </table>
            	<center><p>Agregar Materia</p><button type="button" class="btn btn-success" role="link" onclick="window.location='/addedit/2/3/a/{{user[0]}}'">Añadir</button></center>
    </article>
    <article id="art4">
        <h1>Perfil</h1>
        <!-- Nombre -->
        <form action="/editar/{{user[0]}}/name/teachers" method="post" name="form" class="form-inline" autocomplete="off">
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Nombre de Usuario</div>
            </div>
            <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="{{user[1]}}" name="name" required>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Actualizar</button>
        </form>
        <!-- Correo -->
        <form action="/editar/{{user[0]}}/email/teachers" method="post" name="form" class="form-inline" autocomplete="off">
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Correo Electronico</div>
            </div>
            <input type="email" class="form-control" id="inlineFormInputGroupUsername2" placeholder="{{user[3]}}" name="email" required>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Actualizar</button>
        </form>
        <!-- Institucion -->
        <form action="/editar/{{user[0]}}/ie/teachers" method="post" name="form" class="form-inline" autocomplete="off">
          <div class="input-group mb-3 mr-sm-2">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">Institucion Educativa</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="ie">
              <option value="I.E Antonio Nariño">I.E Antonio Nariño</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Actualizar</button>
        </form>
        <!-- Contraseña -->
        <form action="/editar/{{user[0]}}/password/teachers" method="post" name="form" class="form-inline" autocomplete="off">
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Contraseña Actual</div>
            </div>
            <input type="password" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Contraseña" name="password" requred>
          </div>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Nueva Contraseña</div>
            </div>
            <input type="password" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Contraseña" name="pasword" required>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Actualizar</button>
          <small id="passwordHelpBlock" class="form-text text-muted">
            Recuerda no compartir tu contraseña con nadie.
          </small>
        </form>
        <!-- Eliminar Cuenta -->
        <form action="/editar/{{user[0]}}/drop/teachers" method="post" name="form" class="form-inline" autocomplete="off">
        	<div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Eliminar Cuenta</div>
            </div>
							<button type="submit" class="btn btn-danger" onclick="pregunta(event)">Eliminar Cuenta</button>
          </div>
    </article>
</div>
</div>
{% endblock %}