app/common/models.py
#!/usr/bin/python
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Ie(db.Model):
    __tablename__ = "instituciones"
    #Atributos
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String, nullable = False)
    #Metodos
    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
    @staticmethod
    def get_by_id(id):
        return Ie.query.get(id)
    @staticmethod
    def get_by_name(name):
        return Ie.query.filter_by(name = name).first()

class Perfil(db.Model):
    __tablename__ = "perfil"
    #Atributos
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String, nullable = False)
    #Metodos
    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
    @staticmethod
    def get_by_id(id):
        return Perfil.query.get(id)
    @staticmethod
    def get_by_name(name):
        return Perfil.query.filter_by(name = name).first()

class User(db.Model, UserMixin):
    __tablename__ = "usuarios"
    #Atributos
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String, nullable = False)
    email = db.Column(db.String, unique = True, nullable = False)
    ie = db.Column(db.Integer, db.ForeignKey("instituciones.id", ondelete = "CASCADE"), nullable = False)
    password = db.Column(db.String, nullable = False)
    perfil = db.Column(db.Integer, db.ForeignKey("perfil.id", ondelete = "CASCADE"), nullable = False)
    is_admin = db.Column(db.Boolean, default = False)
    #Metodos
    def __repr__(self):
        return f"<user {self.email}>"
    def set_password(self, password):
        self.password = generate_password_hash(password)
    def check_password(self, password):
        return check_password_hash(self.password, password)
    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
    @staticmethod
    def get_by_id(id):
        return User.query.get(id)
    @staticmethod
    def get_by_email(email):
        return User.query.filter_by(email = email).first()

app/__init__.py
#!/usr/bin/python
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from .common.models import db

login_manager = LoginManager()

def create_app(settings_module='config.development'):

    app = Flask(__name__)
    app.config.from_object(settings_module)

    login_manager.init_app(app)
    login_manager.login_view = "users.log"

    db.init_app(app)
    with app.app_context():
        db.create_all()

    #Blueprints
    from .private import private_bp
    app.register_blueprint(private_bp)

    from .public import public_bp
    app.register_blueprint(public_bp)

    from .users import users_bp
    app.register_blueprint(users_bp)

    return app

app/private/__init__.py
#!/usr/bin/python
from flask import Blueprint

private_bp = Blueprint("private", __name__, template_folder = "templates/private", static_folder = "static/private")

from . import routes

app/private/routes.py
#!/usr/bin/python
from flask import render_template, redirect, url_for
from flask_login import logout_user, login_required

from . import private_bp
from app import login_manager
from app.common.models import User

@private_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("public.index"))

@private_bp.route("/usuario")
@login_required
def logueado():
    return render_template("students.html")

@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(int(user_id))

app/users/__init__.py
#!/usr/bin/python
from flask import Blueprint

users_bp = Blueprint("users", __name__, template_folder = "templates/users")

from . import routes

app/users/routes.py
#!/usr/bin/python
from flask import render_template, request, redirect, url_for
from flask_login import current_user, login_user
from werkzeug.urls import url_parse

from .form import LoginForm, SignupForm
from app.common.models import User
from . import users_bp

@users_bp.route('/login', methods = ["GET", "POST"])
def log():
    if current_user.is_authenticated:
        return redirect(url_for("private.logueado"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_email(form.email.data)
        if user is not None and user.check_password(form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for("private.logueado")
            return redirect(next_page)
    return render_template("log-in.html", form = form, title = "Iniciar Sesion")

@users_bp.route('/register', methods = ["GET", "POST"])
def sign():
    if current_user.is_authenticated:
        return redirect(url_for("private.logueado"))
    form = SignupForm()
    error = None
    if form.validate_on_submit():
        user = User.get_by_email(form.email.data)
        if user is not None:
            error = f"El email {form.email.data} ya está siendo utilizado por otro usuario"
        else:
            user = User(name = form.name.data, email = form.email.data, ie = form.ie.data, perfil = form.perfil.data)
            user.set_password(form.password.data)
            user.save()
            login_user(user, remember = True)
            next_page = request.args.get('next', None)
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for("private.logueado")
            return redirect(next_page)
    return render_template("sign-up.html", form = form, error = error, title = "Registarse")

app/templates/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- bootstrap-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Links -->
  <link rel="stylesheet" href="{{url_for('static', filename = 'css/base.css')}}">
  <link rel="icon" href="{{url_for('static', filename = 'media/logo.png')}}" type="image/png">
  <title>{{ title }}</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{url_for('public.index')}}">LAPBOOK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('public.index')}}">Inicio<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.log')}}">Iniciar Sesion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.sign')}}">Crear Cuenta</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% if error %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ error }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <!-- Footer -->
  <footer class="page-footer font-small blue">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">&copy; 2019 Copyright:
      <a href="{{url_for('public.index')}}">LAPBOOK</a>
    </div>
  </footer>
  <!-- Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <!-- Script -->
  <script type="text/javascript" src="{{url_for('static', filename = 'js/base.js')}}"></script>
</body>

</html>